name: publish

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy to VS Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - run: corepack enable && pnpm install --frozen-lockfile

      - name: Publish to VS Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          dependencies: false
